In [2]:
import numpy as np

## Creating a numpy array

In [3]:
myarray=np.array([3,6,32,7])

In [4]:
myarray

array([ 3,  6, 32,  7])

In [5]:
myarray1=np.array([3,6,32,7],np.int8)

In [6]:
myarray1

array([ 3,  6, 32,  7], dtype=int8)

In [7]:
myarray2=np.array([3,6,377777,7],np.int32) # can also use np.int8 and np.int64
myarray2

array([     3,      6, 377777,      7], dtype=int32)

In [8]:
myarray = np.array([[3, 6, 32, 7]])  # 2D array
myarray[0,1]

np.int64(6)

In [9]:
myarray.shape

(1, 4)

In [10]:
myarray=np.array([3, 6, 32, 7]) # 1D array
myarray[1]

np.int64(6)

In [11]:
myarray.shape

(4,)

In [12]:
myarray = np.array([[3, 6, 32, 7]])
myarray[0,1]=45
myarray

array([[ 3, 45, 32,  7]])

## Array Creation: Conversion from other Python structures

In [13]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])

In [14]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [15]:
listarray.dtype

dtype('int64')

In [16]:
listarray.size

9

In [17]:
listarray.shape

(3, 3)

In [18]:
np.array({34,23,23})

array({34, 23}, dtype=object)

## Intrinsic numpy creation objects

In [19]:
zeros=np.zeros((2,5))

In [20]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
zeros.dtype

dtype('float64')

In [22]:
zeros.shape

(2, 5)

In [23]:
rng=np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
lspace=np.linspace(1,4,10) # to give 10 equally spaced elements between 1 to 4
lspace

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [25]:
emp=np.empty((4,6)) # it will give random elements in a 4*6 matrix format
emp

array([[4.49828734e-315, 0.00000000e+000, 4.55811574e-315,
        6.92822870e-310, 6.92820535e-310, 6.92820535e-310],
       [6.92820535e-310, 6.92820535e-310, 6.92820535e-310,
        6.92820535e-310, 6.92820535e-310, 6.92820535e-310],
       [6.92820535e-310, 6.92820535e-310, 6.92820535e-310,
        6.92820535e-310, 6.92820535e-310, 6.92820535e-310],
       [6.92820535e-310, 6.92820535e-310, 6.92820535e-310,
        6.92820535e-310, 6.92820535e-310, 6.92820535e-310]])

In [26]:
emp_like=np.empty_like(lspace)

In [27]:
emp_like

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [28]:
ide=np.identity(45) # a 45*45 identity matrix
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [29]:
ide.shape

(45, 45)

In [33]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
arr=arr.reshape(3,33)

In [37]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [38]:
arr= arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [39]:
arr.shape

(99,)

In [40]:
x=[[1,2,3],[4,5,6],[7,1,0]]
x

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [42]:
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [43]:
ar.sum(axis=0)

array([12,  8,  9])

In [44]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [45]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [46]:
ar.flat

In [47]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [48]:
ar.ndim

2

In [49]:
ar.size

9

In [50]:
ar.nbytes

72

In [51]:
one=np.array([1,3,4,634,2])

In [52]:
one.argmax()

np.int64(3)

In [53]:
one.argmin()

np.int64(0)

In [54]:
one.argsort()

array([0, 4, 1, 2, 3])

In [55]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [57]:
ar.argmin()

np.int64(8)

In [58]:
ar.argmax()

np.int64(6)

In [59]:
ar.argmax(axis=0)

array([2, 1, 1])

In [60]:
ar.argmax(axis=1)

array([2, 2, 0])

In [61]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [62]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [63]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [64]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [65]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [66]:
ar2=np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [67]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [68]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [69]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [70]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [71]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [72]:
ar.sum()

np.int64(29)

In [74]:
ar.max()

np.int64(7)

In [75]:
ar.min()

np.int64(0)

In [76]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [77]:
np.count_nonzero(ar)

8

In [78]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [79]:
import sys

In [80]:
py_ar=[0,4,55,2]

In [81]:
np_ar=np.array(py_ar)

In [82]:
sys.getsizeof(1)*len(py_ar)

112

In [84]:
np_ar.itemsize*np_ar.size

32